### ISSUE TITLE
Propose a "smart" docker suggestions

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-oh-my-zsh-plugin#10]
Currently all the docker aliases are basically a shortcut to run the full docker command
`jhmysqlup` -> `docker-compose -f src/main/docker/mysql.yml up -d`

All the aliases have the same patten
`docker-compose -f src/main/docker/<COMPONENT>.yml <COMMAND>`

The aim would be to create a oh-my-zsh function fo support auto-suggestions about docker components and commands.

The suggestion relies on 2 steps, first the components are basically the YAML file name present in the `src/main/docker` directory:
`basename $(ls src/main/docker/*.yml) | cut -d '.' -f 1)`

Regarding the command, letss keep it simple, a switch on `up`, `down` and `logs` commands is good enough to start.

I'm a total noob about oh-my-zsh auto-suggestions scripts. I'll try to propose something but if someone is familiar is comfortable with this kind of script, help is welcome.

**Comment by jdubois** [comment]
Yes we wanted to have auto-completion too, it's just we are also totally new to how this works! If you have time, please go ahead!

**Comment by pascalgrimaud** [comment]
auto completion already done directly in the main generator with https://github.com/jhipster/generator-jhipster/pull/5726

We can now use: `jh`, `space`, then `tab` and we got:
```shell
➜ jh
completion       --version     --debug     upgrade    service    -V      -d                                                                                                         
docker-compose   cloudfoundry  export-jdl  entity     client     ci-cd   aws     app                                                                                                
rancher-compose  kubernetes    import-jdl  openshift  languages  server  heroku  info  --
```
