### ISSUE TITLE
shortcut docker app.yml

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-oh-my-zsh-plugin#11]
Is there a reason why `docker-compose -f src/main/docker/app.yml up -d` does not have any shortcut?

If not, I can create a PR with `jhappup`, `jhappdown`, `jhappstop` and `jhapplogs` added.
And maybe another one with `jhdock` (package docker) and `jhappup` combined: `jhdockup`?

**Comment by pascalgrimaud** [comment]
jhappup, jhappdown, jhappstop and jhapplog sound good!
