### ISSUE TITLE
jhipster-cmder-plugin

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-oh-my-zsh-plugin#9]
@jdubois 
https://github.com/anjia0532/jhipster-cmder-plugin

**Comment by jdubois** [comment]
Thanks but I don't understand what you want to do: that's a PowerShell plugin, and this is the oh-my-zsh plugin...

**Comment by anjia0532** [comment]
@jdubois 
[cmder-powershell-plugin](https://github.com/anjia0532/jhipster-cmder-plugin/blob/master/user-profile.ps1) is copy from jhipster-oh-my-zsh-plugin 

[jhipster shell plugins](https://jhipster.github.io/shell-plugins/)  only 2 shell, and both of them not support windows(Unless run it with [cygwin](https://cygwin.com/))

the [cmder](http://cmder.net/),[github/cmder](https://github.com/cmderdev/cmder) is Portable console emulator for Windows,it's so good.
